# The amount of time players have to hide without the seekers (in ticks)
# Default: 4200 (3:30)
hide_time: 4200

# The amount of a time a match lasts (in ticks)
# Default: 24000 (20:00)
match_time: 24000

# The times before the start_shrink_time when a warning will be sent for the match stops
match_stop_warning_times:
  - 12000 # This is 10 mins, so thus a warning is sent 10 mins *before* the match ends
  - 6000 # 5 mins
  - 2400 # 2 mins
  - 1200 # 1 mins
  - 600 # 30 seconds
  - 200 # 10 seconds
  - 180
  - 160
  - 140
  - 120
  - 100
  - 80
  - 60
  - 40
  - 20

# How much time it takes for the players to start glowing (in ticks)
# Default: 0 (starts the interval immediately)
glow_start: 0

# The amount of time in-between each time the hiders glow (in ticks)
# Default: 3600 (3:00)
glow_interval: 3600

# Lobby location details
lobby:
  world: world # Default: "world" - this refers to the primary world
  x: 0.0 # Default: 0.0
  y: 0.0 # Default: 0.0
  z: 0.0 # Default: 0.0

# Game world border details
border:
  # The initial size of the border, before any shrinking (in blocks) (0 for no border)
  # Default: 250
  initial_size: 250

  # The x and z coordinates of the center of the border
  center:
    x: 0.0 # Default: 0.0
    z: 0.0 # Default: 0.0

  # The times before the start_shrink_time when a warning will be sent for the shrinking of the border
  warning_times:
    - 200 # This is 10 seconds, so thus a warning is sent 10 seconds *before* the border starts to shrink
    - 180
    - 160
    - 140
    - 120
    - 100
    - 80
    - 40
    - 20

  # How much time it takes for the border to start shrinking (in ticks)
  # Default: 12000 (10:00)
  start_shrink_time: 12000

  # The amount of time in-between each border shrinking (in ticks)
  # Default: 1200 (01:00)
  shrink_interval: 1200

  # The amount of blocks the border shrinks by (in blocks)
  # Default: 10.0
  shrink_size: 10.0

# Debug mode
debug: true