# The amount of time players have to hide without the seekers (in ticks)
# Default: 4200 (3:30)
hide_time: 4200

# The amount of time seekers have to seek (in ticks)
# Default: 24000 (20:00)
seek_time: 24000

# How much time it takes for the border to start shrinking (in ticks)
# Default: 12000 (10:00)
border_start_shrink: 12000

# The amount of time in-between each border shrinking (in ticks)
border_shrink_interval:

# The amount of blocks the border shrinks by
# Default: 1
border_shrink_size: 1

# How much time it takes for the players to start glowing (in ticks)
# Default: 0 (starts immediately)
glow_start: 0

# The amount of time in-between each time the hiders glow (in ticks)
# Default: 3600 (3:00)
glow_interval: 3600

# Lobby location details
lobby:
  world: world # Default: "world" - this refers to the primary world
  x: 0.0 # Default: 0.0
  y: 0.0 # Default: 0.0
  z: 0.0 # Default: 0.0

##################################################################################
###                                REGION FLAGS                                ###
### -------------------------------------------------------------------------- ###
### Not every region flag is listed here, just what I thought was necessary to ###
### include. The point of this section is that, if you don't like my settings, ###
###  you can change them. If you want to change other region flags, you can do ###
###                      so through the default commands.                      ###
##################################################################################

region_flags:

  # Whether players are invincible
  # WARNING: Changing this will allow ALL damage types. To prevent this, manually change region flags
  # Default: true
  INVINCIBILITY: true

  # Whether sleeping in a bed is permitted
  # Default: true
  SLEEP: true

  # Whether farmland and turtle eggs can be trampled
  # Default: false
  TRAMPLE_BLOCKS: false

  # Whether items can be rotated within item frames
  # Default: false
  ITEM_FRAME_ROTATE: false

  # Whether explosions can do damage
  # Default: false
  OTHER_EXPLOSION: false

  # Whether fire can spread
  # Default: false
  FIRE_SPREAD: false

  # Whether mobs can spawn
  # WARNING: Turning this to true will likely allow block damage via mobs
  # Default: false
  MOB_SPAWNING: false

  # Whether lava can start fires
  # Default: false
  LAVA_FIRE: false

  # Whether items can be picked up
  # Default: false
  ITEM_PICKUP: true

  # Whether items can be dropped
  # Default: false
  ITEM_DROP: false

  # Whether XP drops are permitted
  # Default: false
  EXP_DROPS: false

  # Whether player should naturally lose hunger due to saturation/exhaustion levels
  # Default: false
  HUNGER_DRAIN: false